# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Blog
paginate:       10
baseurl:        ""
url:            "https://ryyang.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         
  url:          
  email:        

# Custom vars
version:        
github:
  repo:         https://ryyang.github.io/

# Gems
gems:
  - jekyll-paginate
